# Generated by Django 4.2.10 on 2024-02-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_inventory_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(default='None', max_length=500, null='True'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='./static/img/salad.jpg', null='True', upload_to='menu-images/'),
        ),
    ]
