# Generated by Django 4.2.10 on 2024-02-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menu_description_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(null='True'),
        ),
    ]
