# Generated by Django 4.2.10 on 2024-02-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menuitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=500, null='True'),
        ),
    ]
